name: Update Profile
on:
  schedule:
    # 每天 0:00 运行一次
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ScottSloan
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai